### ISSUE TITLE
Can't use it yet

### ISSUE THREAD

**Issue by fxfactorial** [little-arhat/ppx_jsobject_conv#1]
I want to use this but I'm starting from a baseline of 4.03.0 and ppx_deriving 4.0. I tried playing with making ppx_jsobject_conv depend on >= 4.0 but that blew up with 

``` shell
ppx_js_object_conv needs to be installed.
The following dependencies couldn't be met:
  - ppx_js_object_conv -> ppx_deriving >= 4.0
  - ppx_js_object_conv -> ppx_type_conv >= 113.24.00 -> ppx_driver < 113.25.00 -> ppx_core < 113.25.00
  - ppx_js_object_conv -> ppx_type_conv >= 113.24.00 -> ppx_deriving < 4.0
Your request can't be satisfied:
  - Conflicting version constraints for ppx_deriving
  - ppx_core<113.25.00 is not available because your system doesn't comply with ocaml-version >= "4.02.3" & ocaml-version < "4.03.0".

No solution found, exiting
```

So I guess its just a matter of time until Jane Street catches up?

**Comment by little-arhat** [comment]
Yeah, it seems `ppx_type_conv-113.33.03` which can be used with `ppx_deriving-4.0` is not available for `4.03.0`, which is quite sad %( . I'll try to figure out what stops Jane Street from updating it, and will file a bug, perhaps. 

If you don't mind me asking, what packages are depend on `ppx_deriving-4.0`?  I have `3.3` installed, and haven't seen any problems yet.

**Comment by fxfactorial** [comment]
Don't remember exactly, wanted to start at high baseline of versioning

**Comment by little-arhat** [comment]
fixed via https://github.com/janestreet/ppx_type_conv/pull/5
