### ISSUE TITLE
No longer compatible with ppx_core 114.35+03

### ISSUE THREAD

**Issue by disteph** [little-arhat/ppx_jsobject_conv#2]
I just had a compilation problem with opam, using Jane Street's opam repository, which is now up to versions 114.35+03 of their packages:

File "src/ppx_jsobject_conv.ml", line 160, characters 33-40:
Warning 42: this use of pcd_loc relies on type-directed disambiguation,
it will not compile with OCaml 4.00 or earlier.
File "src/ppx_jsobject_conv.ml", line 173, characters 40-45:
Error: This expression has type Parsetree.case list
       but an expression was expected of type Ppx_core__.Import.case list
       Type Parsetree.case is not compatible with type
         Ppx_core__.Import.case = Ast_403.Parsetree.case 

They must have changed some stuff in ppx_core that you haven't had the time to integrate yet.
In the meantime you could indicate to opam that your dependency on ppx_core is for the versions of ppx_core up to the previous version...

**Comment by little-arhat** [comment]
@disteph thanks for the report! I've created the branch with new `ppx_type_conv`.

**Comment by disteph** [comment]
Great, thanks!
Actually, I seem to already have a problem in the 4.03.0 switch where the official opam repo already has ppx_type_conv.v0.9.0 (so it's not so bleeding :-) ), and that gives me a fatal warning:

File "src/ppx_jsobject_conv.ml", line 4, characters 5-17:
Warning 3: deprecated: module Ppx_core.Std
[since 2017-01] Use Ppx_core or Ppx_core.Light instead
File "src/ppx_jsobject_conv.ml", line 1:
Error: Some fatal warnings were triggered (1 occurrences)
Command exited with code 2.

**Comment by little-arhat** [comment]
@disteph https://github.com/ocaml/opam-repository/pull/8818 — I've uploaded new version (0.4.2), compatible with `ppx_type_conv.v.0.9.0`. It should hit the repo soon, I suppose.

Hope that helps!

**Comment by little-arhat** [comment]
@disteph done, 0.4.2 is available, thanks for the report!

**Comment by disteph** [comment]
Great, thanks! It's a great package!
Last thing before closing, though:
pkg/META.in
mentions the dependency on lib ppx_core.for_ppx_deriving
which no longer exists in the new versions of ppx_core
Can you do without the dependency?

**Comment by little-arhat** [comment]
@disteph oh, that bad! Checks have passed in `opam-repository`, but they check installability only, not usage. Pushed fixes, and will do 0.4.3 release right now. Thank you for your help — I've completely missed all these changes with janestreet libs! Appreciate this!
