### ISSUE TITLE
Semantic of Js_of_ocaml.Js.Unsafe.{get, set, delete} is changing

### ISSUE THREAD

**Issue by hhugo** [little-arhat/ppx_jsobject_conv#6]
See https://github.com/ocsigen/js_of_ocaml/pull/997

The change will affect `Js_of_ocaml.Js.Unsafe.{get, set, delete}` called with ocaml string keys that are not ascii.

A trivial fix is to call them with javascript string instead.
`Js.Unsage.get o (Js.string k)` instead of `Js.Unsafe.get o k`

**Comment by little-arhat** [comment]
@hhugo thanks for heads up! Will this `Js.Unsage.get o (Js.string k) instead of Js.Unsafe.get o k` work with current js_of_ocaml?

**Comment by hhugo** [comment]
Yes
